# coding: utf-8

"""
    Bundesnetzagentur Strommarktdaten

    Bundesnetzagentur Strommarktdaten

    The version of the OpenAPI document: 0.0.1
    Contact: kontakt@bund.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "smard"
VERSION = "0.1.0"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Bundesnetzagentur Strommarktdaten",
    author="BundesAPI",
    author_email="kontakt@bund.dev",
    url="https://github.com/bundesAPI/smard-api",
    keywords=["OpenAPI", "OpenAPI-Generator", "Bundesnetzagentur Strommarktdaten"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Bundesnetzagentur Strommarktdaten
    """,  # noqa: E501
    package_data={"smard": ["py.typed"]},
)
