# coding: utf-8

"""
    Bundesnetzagentur Strommarktdaten

    Bundesnetzagentur Strommarktdaten

    The version of the OpenAPI document: 0.0.1
    Contact: kontakt@bund.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from deutschland.smard.models.time_series2 import TimeSeries2  # noqa: E501

class TestTimeSeries2(unittest.TestCase):
    """TimeSeries2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimeSeries2:
        """Test TimeSeries2
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimeSeries2`
        """
        model = TimeSeries2()  # noqa: E501
        if include_optional:
            return TimeSeries2(
                meta_data = smard.models.time_series_meta_data.TimeSeries_meta_data(
                    version = 56, 
                    created = 56, ),
                series = [
                    smard.models.time_series2_series_inner.TimeSeries2_series_inner(
                        values = [
                            smard.models.time_series2_series_inner_values_inner.TimeSeries2_series_inner_values_inner(
                                timestamp = 1.337, 
                                versions = [
                                    smard.models.time_series2_series_inner_values_inner_versions_inner.TimeSeries2_series_inner_values_inner_versions_inner(
                                        value = 1.337, 
                                        name = null, )
                                    ], )
                            ], )
                    ]
            )
        else:
            return TimeSeries2(
        )
        """

    def testTimeSeries2(self):
        """Test TimeSeries2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
