# coding: utf-8

"""
    Bundesnetzagentur Strommarktdaten

    Bundesnetzagentur Strommarktdaten

    The version of the OpenAPI document: 0.0.1
    Contact: kontakt@bund.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from deutschland.smard.models.time_series_meta_data import TimeSeriesMetaData  # noqa: E501

class TestTimeSeriesMetaData(unittest.TestCase):
    """TimeSeriesMetaData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimeSeriesMetaData:
        """Test TimeSeriesMetaData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimeSeriesMetaData`
        """
        model = TimeSeriesMetaData()  # noqa: E501
        if include_optional:
            return TimeSeriesMetaData(
                version = 56,
                created = 56
            )
        else:
            return TimeSeriesMetaData(
        )
        """

    def testTimeSeriesMetaData(self):
        """Test TimeSeriesMetaData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
