# coding: utf-8

"""
    Bundesnetzagentur Strommarktdaten

    Bundesnetzagentur Strommarktdaten

    The version of the OpenAPI document: 0.0.1
    Contact: kontakt@bund.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from deutschland.smard.models.time_series import TimeSeries  # noqa: E501

class TestTimeSeries(unittest.TestCase):
    """TimeSeries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimeSeries:
        """Test TimeSeries
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimeSeries`
        """
        model = TimeSeries()  # noqa: E501
        if include_optional:
            return TimeSeries(
                meta_data = smard.models.time_series_meta_data.TimeSeries_meta_data(
                    version = 56, 
                    created = 56, ),
                series = [
                    [
                        1.337
                        ]
                    ]
            )
        else:
            return TimeSeries(
        )
        """

    def testTimeSeries(self):
        """Test TimeSeries"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
