# coding: utf-8

"""
    Bundesnetzagentur Strommarktdaten

    Bundesnetzagentur Strommarktdaten

    The version of the OpenAPI document: 0.0.1
    Contact: kontakt@bund.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from deutschland.smard.models.indices import Indices  # noqa: E501

class TestIndices(unittest.TestCase):
    """Indices unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Indices:
        """Test Indices
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Indices`
        """
        model = Indices()  # noqa: E501
        if include_optional:
            return Indices(
                timestamps = [
                    56
                    ]
            )
        else:
            return Indices(
        )
        """

    def testIndices(self):
        """Test Indices"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
